---
version: '3.2'
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    hostname: adguard
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "8853:8853/udp"
    environment:
      TZ: Europe/Madrid
    volumes:
      - '/root/docker/adguardhome/work/:/opt/adguardhome/work/'
      - '/root/docker/adguardhome/conf/:/opt/adguardhome/conf/'
    cap_add:
      - NET_ADMIN
